Repository Afordin/web-afordin, pull requests merged in 2025-04, with the labels that each got.

#67 feat: add header video to Hero component
  public/media/header.webm
  src/components/Hero.astro
Labels: bug

#104 Feature/animacion svgs
  src/components/Nav.astro
  src/components/ui/DiscordIcon.astro
  src/components/ui/GitHubIcon.astro
  src/styles/app.css
Labels: conflicts

#108 style: update contributors avatar hover effect and refactor
  src/assets/Github.svg
  src/assets/LinkedIn.svg
  src/components/Footer.astro
  src/components/FooterContributors.astro
  src/components/FooterDesignersContributors.astro
  src/components/ui/Avatar.astro
  src/types/index.d.ts
Labels: enhancement

#112 feat: add smooth scrolling behavior and update section IDs for navigation
  src/components/Community.astro
  src/components/Contributors.astro
  src/components/Hero.astro
  src/components/LastProjects.astro
  src/components/Nav.astro
  src/components/Values.astro
  src/layouts/Layout.astro
Labels: conflicts

#115 Responsive projects & footer
  src/components/Footer.astro
  src/components/FooterContributors.astro
  src/components/Values.astro
  src/layouts/Layout.astro
Labels: conflicts
